homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 247
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Louisville
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

logger:
  default: info
  logs:
      pydukeenergy.api: debug

http:
  api_password: !secret http_password

updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

history_graph:
  duke_energy_usage:
    entities:
      - sensor.power2
    hours_to_show: 744

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
media_player: !include media_player.yaml
cloud: !include cloud.yaml

zwave:
 usb_path: /dev/ttyUSB0
 network_key: !secret zwave_key
 polling_interval: 30000
 device_config:
   sensor.aeotec_dsb09104_home_energy_meter_power_4:
     polling_intensity: 1
     refresh_value: 2

# zha:
#   usb_path: /dev/ttyUSB1
#   database_path: zigbee.db

apcupsd:

wemo:
  static:
    - 192.168.5.33

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: HASS
  keepalive: 60
  username: homeassistant
  password: !secret mqtt_password

octoprint:
  host: 192.168.5.4
  api_key: !secret octoprint_api_key
  bed: false
  number_of_tools: 1

wink:
  local_control: True

camera:
  - platform: mjpeg
    name: living room camera
    mjpeg_url: !secret living_room_camera_url
  - platform: mjpeg
    name: outside camera
    mjpeg_url: !secret outside_camera_url
  - platform: local_file
    name: last outside motion
    file_path: /media/outsidecamera/newest.jpg
  - platform: ffmpeg
    name: Office
    input: -rtsp_transport tcp -i rtsp://192.168.5.63:8554/unicast
  - platform: ffmpeg
    name: printer
    input: -f mjpeg -i http://192.168.5.4:8080/?action=stream -vf "transpose=2, transpose=2"

device_tracker:
  - platform: owntracks_http
    max_gps_accuracy: 200
    new_device_defaults:
      track_new_devices: False
  - platform: unifi_direct
    host: 192.168.5.2
    username: w1ll1am
    password: !secret unifi_password
  - platform: trackr
    username: !secret my_email
    password: !secret trackr_password

alarm_control_panel:
  - platform: manual
    name: "HA Alarm"
    pending_time: 60
    trigger_time: 120
    code: 1234

notify:
  - platform: smtp
    name: sms_billy
    server: smtp.gmail.com
    port: 587
    sender: !secret sender_email
    encryption: starttls
    username: !secret sender_email
    password: !secret sender_email_password
    recipient: !secret billys_number
  - platform: smtp
    name: sms_melina
    server: smtp.gmail.com
    port: 587
    sender: !secret sender_email
    encryption: starttls
    username: !secret sender_email
    password: !secret sender_email_password
    recipient: !secret melinas_number

light:
  - platform: flux_led
    devices:
      192.168.5.53:
        name: under bed light

feedreader:
  urls:
    - http://status.winkapp.com/history.atom

input_select:
  camera_mode:
    name: Camera Mode
    options:
      - "Default"
      - "Door"
      - "Dog"
      - "Off"
    initial: 'Default'
    icon: mdi:camera

shell_command:
  pull_last_motion_event: /bin/bash /media/newest.sh

input_boolean:
  dryer_switch:
   name: Toggle dryer automation
   initial: off
   icon: mdi:sync

cover:
  - platform: mqtt
    name: "Garage Door"
    state_topic: "garage/door/1/status"
    command_topic: "garage/door/1/action"
    availability_topic: "GarHAge/availability"
    qos: 0
    optimistic: false
    retain: false
    payload_open: "OPEN"
    payload_close: "CLOSE"
    payload_stop: "STATE"
    state_open: "open"
    state_closed: "closed"
    payload_available: "online"
    payload_not_available: "offline"
