homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 247
  unit_system: imperial
  time_zone: America/Louisville
  customize: !include customize.yaml

http:
  api_password: !secret http_password

logger:
  default: warn
  logs:
      wink: debug
      pywink.api: debug
      requests.packages.urllib3: critical
      urllib3.exceptions.HeaderParsingError: critical
      urllib3.connectionpool: critical

#discovery:

updater:

frontend:

logbook:

history:

history_graph:
    gr1:
      name: UVB
      entities:
        - sensor.turtle_tank_uvb
      hours_to_show: 4380
      refresh: 300

recorder:

sun:

ios:
  push:
    categories:
      - name: Front Door
        identifier: 'LOCK'
        actions:
          - identifier: 'UNLOCK_DOOR'
            title: 'Yes'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
          - identifier: 'DISMISS'
            title: 'Dismiss'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'

apcupsd:

wemo:
  static:
    - 192.168.5.33

mqtt:
  broker: 192.168.5.5
  port: 1883
  client_id: HASS
  keepalive: 60
  username: homeassistant
  password: !secret mqtt_password

octoprint:
  host: 192.168.5.4
  api_key: !secret octoprint_api_key

wink:
  local_control: True

camera:
  - platform: mjpeg
    mjpeg_url: !secret camera_url

device_tracker:
  - platform: trackr
    username: !secret my_email
    password: !secret trackr_password
  - platform: owntracks
    max_gps_accuracy: 200
  - platform: unifi_direct
    host: 192.168.5.2
    username: w1ll1am
    password: 'rj%va1JA@Z^&^W2w'
    track_new_devices: false

alarm_control_panel:
  - platform: manual
    name: "HA Alarm"
    pending_time: 60
    trigger_time: 120

notify:
  - platform: smtp
    name: sms_billy
    server: smtp.gmail.com
    port: 587
    sender: !secret sender_email
    encryption: starttls
    username: !secret sender_email
    password: !secret sender_email_password
    recipient: !secret billys_number
  - platform: smtp
    name: sms_melina
    server: smtp.gmail.com
    port: 587
    sender: !secret sender_email
    encryption: starttls
    username: !secret sender_email
    password: !secret sender_email_password
    recipient: !secret melinas_number

zone: !include zones.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
automation: !include automations.yaml
script: !include scripts.yaml
group: !include groups.yaml
media_player: !include media_player.yaml
alexa:
intent_script: !include alexa.yaml

################################################
################Input booleans#################
################################################

input_boolean:
  dryer_switch:
   name: Toggle dryer automation
   initial: off
   icon: mdi:sync
  on_vacation:
    name: On Vacation
    initial: off
    icon: mdi:beach_access

cover:
  - platform: command_line
    covers:
      garage_door:
        command_open: /usr/bin/curl 192.168.5.28:3000/toggleDoor
        command_close: /usr/bin/curl 192.168.5.28:3000/toggleDoor
        command_stop: /usr/bin/curl 192.168.5.28:3000/toggleDoor
        command_state: /usr/bin/curl 192.168.5.28:3000
        value_template: >
          {%- if is_state("sensor.arest_sensor_garage", "Closed") -%}
          0
          {%- else -%}
          100
          {%- endif %}
        friendly_name: Garage Door

light:
  - platform: flux_led
    devices:
      192.168.5.53:
        name: under bed light

feedreader:
  urls:
    - http://status.winkapp.com/history.atom

input_select:
  camera_mode:
    name: Camera Mode
    options:
      - "Default"
      - "Door"
      - "Dog"
      - "Off"
      - "Reboot"
      - "Snapshot"
    initial: 'Default'
    icon: mdi:camera
